/**
 * Process photos script.
 *
 * Scans public/photos/ for HEIC, JPG, PNG files:
 *   - Converts HEIC → JPG (browsers can't display HEIC)
 *   - Reads EXIF GPS + date from each image
 *   - Generates src/lib/photos.ts with all entries auto-populated
 *
 * Usage:
 *   node scripts/process-photos.mjs
 *
 * After running, edit src/lib/photos.ts to:
 *   - Fix any missing city/country names
 *   - Add captions
 *   - Adjust GIFT_TITLE and GIFT_SUBTITLE
 */

import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, basename, extname, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import exifr from "exifr";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const PHOTOS_DIR = join(ROOT, "public", "photos");
const OUTPUT_FILE = join(ROOT, "src", "lib", "photos.ts");

const SUPPORTED = [".heic", ".heif", ".jpg", ".jpeg", ".png", ".webp"];

async function main() {
  if (!existsSync(PHOTOS_DIR)) {
    console.error("❌ public/photos/ folder not found. Create it and add your photos.");
    process.exit(1);
  }

  const files = readdirSync(PHOTOS_DIR)
    .filter((f) => SUPPORTED.includes(extname(f).toLowerCase()))
    .sort();

  if (files.length === 0) {
    console.error("❌ No photos found in public/photos/. Add HEIC, JPG, or PNG files.");
    process.exit(1);
  }

  console.log(`Found ${files.length} photos. Processing...`);

  const entries = [];

  for (const file of files) {
    const filePath = join(PHOTOS_DIR, file);
    const ext = extname(file).toLowerCase();
    let servePath;

    // Convert HEIC to JPG (browsers can't display HEIC)
    if (ext === ".heic" || ext === ".heif") {
      const jpgName = basename(file, ext) + ".jpg";
      const jpgPath = join(PHOTOS_DIR, jpgName);
      // Skip if already converted
      if (existsSync(jpgPath)) {
        console.log(`  ⏭ ${file} — already converted to ${jpgName}`);
        servePath = `/photos/${jpgName}`;
      } else {
        try {
          console.log(`  Converting ${file} → ${jpgName}`);
          await sharp(filePath).jpeg({ quality: 85 }).toFile(jpgPath);
          servePath = `/photos/${jpgName}`;
        } catch (convErr) {
          console.log(`  ⚠️  ${file} — HEIC conversion failed (convert manually to JPG)`);
          console.log(`     Tip: Open in Photos app → Save As → JPG, or use https://heictojpg.com`);
          servePath = null; // skip this file
        }
      }
    } else {
      servePath = `/photos/${file}`;
    }

    if (!servePath) continue;

    // Read EXIF
    let lat = null;
    let lng = null;
    let date = null;

    try {
      const exif = await exifr.parse(filePath, {
        gps: true,
        pick: ["DateTimeOriginal", "CreateDate", "GPSLatitude", "GPSLongitude"],
      });
      if (exif) {
        if (exif.latitude != null && exif.longitude != null && !isNaN(exif.latitude) && !isNaN(exif.longitude)) {
          lat = Math.round(exif.latitude * 10000) / 10000;
          lng = Math.round(exif.longitude * 10000) / 10000;
        }
        const d = exif.DateTimeOriginal || exif.CreateDate;
        if (d instanceof Date) {
          date = d.toISOString().split("T")[0];
        }
      }
    } catch (e) {
      // EXIF read failed — user will fill in manually
    }

    const name = basename(file, ext).replace(/[-_]/g, " ");
    entries.push({
      id: String(entries.length + 1),
      src: servePath,
      city: "TODO",
      country: "TODO",
      lat,
      lng,
      date: date || "2024-01-01",
      caption: name,
    });

    const gpsStatus = lat != null ? `📍 ${lat}, ${lng}` : "⚠️  No GPS";
    const dateStatus = date || "⚠️  No date";
    console.log(`  ✓ ${file} — ${gpsStatus} — ${dateStatus}`);
  }

  // Generate photos.ts
  const tsContent = `/**
 * YOUR PHOTOS — Auto-generated by scripts/process-photos.mjs
 *
 * Edit the city/country/caption fields below.
 * Photos with "TODO" need manual GPS coordinates (lat/lng).
 * Photos are displayed in chronological order by \`date\`.
 */

export interface GiftPhoto {
  id: string;
  src: string;
  city: string;
  country: string;
  lat: number;
  lng: number;
  date: string;
  caption?: string;
}

export const GIFT_TITLE = "Our Adventure";
export const GIFT_SUBTITLE = "A journey to remember";

export const PHOTOS: GiftPhoto[] = ${JSON.stringify(entries, null, 2).replace(/"(\w+)":/g, "$1:")};
`;

  writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`\n✅ Generated src/lib/photos.ts with ${entries.length} entries.`);
  console.log(`\n📝 Next steps:`);
  console.log(`   1. Open src/lib/photos.ts`);
  console.log(`   2. Fill in city/country for entries marked "TODO"`);
  console.log(`   3. Add lat/lng for any photos without GPS data`);
  console.log(`   4. Edit GIFT_TITLE and GIFT_SUBTITLE`);
  console.log(`   5. Add captions`);

  if (entries.some((e) => e.lat === null)) {
    console.log(`\n⚠️  ${entries.filter((e) => e.lat === null).length} photos have no GPS. You'll need to add coordinates manually.`);
    console.log(`   Tip: Use Google Maps — right-click a location → "What's here?" to get lat/lng.`);
  }
}

main().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
